# GBackup Config File
# The level of compression you want your backups to have
CompressionLevel: 9
# How old a backup can be before it's deleted
DaysBeforeDeletion: 7
# The Prefix of the backup
ServerName: ServerName
# Date and Time Format
DateFormat: "yyyy-MM-dd-HH-mm-ss"