name: GBackup
version: ${project.version}
main: net.stormmc.JordanPlayz158.GBackup
api-version: 1.13
author: JordanPlayz158
description: This is a Backup Plugin that uses tar and gzip to compress your backups to the smallest size!
website: https://stormmc.net
commands:
  gbackup:
    description: Backups the server!
    permission: gbackup.backup
  gcleanup:
    description: Cleans up old backups!
    permission: gbackup.cleanup
  greload:
    description: Reloads config file!
    permission: gbackup.reload

permissions:
  gbackup.*:
    description: Gives access to all GBackup commands!
    default: op
    children:
      gbackup.backup: true
      gbackup.cleanup: true
      gbackup.reload: true
  gbackup.backup:
    description: Gives access to /gbackup
    default: op
  gbackup.cleanup:
    description: Gives access to /gcleanup
    default: op
  gbackup.reload:
    description: Gives access to /greload
    default: op